Add heap and n queens problem
AHarishma/Data-Structures pull request #2
Opened 2023-11-26 18:36 UTC by AHarishma

2023-11-26 19:04 UTC, venkatyuva requested changes
Please correct these and merge them.

2023-11-26 19:04 UTC, venkatyuva commented on src/com.company/heap/MagicianAndChocolates.java
> +            priorityQueue.add((int) Math.floor(maxElement / 2));
Math.floor function is not required as division by 2 will always give floor value only.

2023-11-26 19:04 UTC, venkatyuva commented on src/com.company/heap/MishaAndCandies.java
> +                int chocolateEatenCount = (int) Math.floor(minElement / 2);
Math.floor is not required as division by 2 will always give floor value. Also typecasting to int is also not required which will be handled automatically.

2023-11-27 08:19 UTC, AHarishma commented on src/com.company/heap/MagicianAndChocolates.java
> +            priorityQueue.add((int) Math.floor(maxElement / 2));
changed

2023-11-27 08:19 UTC, AHarishma commented on src/com.company/heap/MishaAndCandies.java
> +                int chocolateEatenCount = (int) Math.floor(minElement / 2);
changed

2023-11-27 08:20 UTC, merged

2023-11-27 16:22 UTC, madhusdhnn commented on src/com.company/backtracking/NQueens.java
> +    void solve(int n, int row, List<Integer> currentList, List<List<Integer>> result) {
Make it private

2023-11-27 16:22 UTC, madhusdhnn commented on src/com.company/backtracking/NQueens.java
> +    public static void main(String[] args) {
You may move this driver code to Junit test case. It will help you think of different inputs possible

2023-11-27 16:22 UTC, madhusdhnn commented on src/com.company/heap/Heap.java
> +public class Heap {
Rewrite this file into a proper, formatted, and readable code. Take time. No need to hurry.

2023-11-27 16:22 UTC, madhusdhnn commented on src/com.company/heap/MagicianAndChocolates.java
> +        PriorityQueue<Integer> priorityQueue = new PriorityQueue<>(Collections.reverseOrder());
Name the variables properly. Eg: `minHeap`

2023-11-29 14:17 UTC, AHarishma commented on src/com.company/backtracking/NQueens.java
> +    void solve(int n, int row, List<Integer> currentList, List<List<Integer>> result) {
added

2023-11-29 14:17 UTC, AHarishma commented on src/com.company/backtracking/NQueens.java
> +    public static void main(String[] args) {
Will add Junit test cases in future commits

2023-11-29 14:18 UTC, AHarishma commented on src/com.company/heap/Heap.java
> +public class Heap {
Will change this in future commits

2023-11-29 14:25 UTC, AHarishma commented on src/com.company/heap/MagicianAndChocolates.java
> +        PriorityQueue<Integer> priorityQueue = new PriorityQueue<>(Collections.reverseOrder());
changed